[package]

name = "png"
version = "0.1.0"
authors = ["The Servo Project Developers"]

links = "png_sys"
build = "build.rs"

[dependencies.png_sys]
path = "png-sys"

[build-dependencies.gcc]
git = "https://github.com/alexcrichton/gcc-rs"
